plugin:
  name: easydb-editor-field-visibility-plugin
  version: 1.1
  url: https://github.com/programmfabrik/easydb-editor-field-visibility-plugin
  displayname:
    de-DE: Feldsichtbarkeit auf Basis eines anderen Feldes
    en-US: Fieldvisibility based on another fields value
  info:
    de-DE: Custom Mask Splitter to show / hide fields in Editor, depending on other fields.
    en-US: Custom Mask Splitter to show / hide fields in Editor, depending on other fields.
  server:
    api-version:
      require: 1
  webfrontend:
    url: easydb-editor-field-visibility.js
    l10n: l10n/
